#!/usr/bin/env bash

DEFAULT_WEB_BROWSER=brave-browser

DEFAULT_SEARCH_ENGINE_PAGE="https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=libvirt&"

DEFAULT_QUERY_PARAMETER="q=@"

usage(){
cat <<EOS
Usage:
   IN: echo ubuntu | $0
  OUT: $DEFAULT_SEARCH_ENGINE_PAGE?q=ubuntu&utf8=%E2%9C%93&sort=downloads&provider=libvirt
EOS

exit 0

}

is_single_row(){
  #単一行チェック
  local CNT=0
  while read ln;do
    [ $(echo $ln | grep -c "0a") -eq 1 ] && CNT=$((CNT + 1))
  done < <(echo "$@" | xxd -ps -c1)
  [ $CNT -gt 1 ] || echo 0
  [ $CNT -gt 1 ] && echo 1
}

main(){
  n="$(cat -)";

  [ -z "$n" ] && usage

  if [[ $(is_single_row "$n") -eq 0 ]];then
    echo "$n" | xargs -I@ $DEFAULT_WEB_BROWSER "$DEFAULT_SEARCH_ENGINE_PAGE?$DEFAULT_QUERY_PARAMETER" 1>/dev/null 2>&1
  else
    usage
  fi
}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || echo -ne "$@" | main
