#!/usr/bin/env bash

DEFAULT_WEB_BROWSER=brave-browser

DEFAULT_SEARCH_ENGINE_PAGE="https://dev.to/search"

DEFAULT_QUERY_PARAMETER="q=@&filters=class_name:Article"

usage(){
cat <<EOS
Usage:
   IN: echo systemd-nspawn | $0
  OUT: $DEFAULT_SEARCH_ENGINE_PAGE?q=systemd-nspawn&filters=class_name:Article
EOS

exit 0

}

is_single_row(){
  #単一行チェック
  local CNT=0
  while read ln;do
    [ $(echo $ln | grep -c "0a") -eq 1 ] && CNT=$((CNT + 1))
  done < <(echo "$@" | xxd -ps -c1)
  [ $CNT -gt 1 ] || echo 0
  [ $CNT -gt 1 ] && echo 1
}

main(){
  n="$(cat -)";

  [ -z "$n" ] && usage

  if [[ $(is_single_row "$n") -eq 0 ]];then
    echo "$n" | xargs -I@ $DEFAULT_WEB_BROWSER "$DEFAULT_SEARCH_ENGINE_PAGE?$DEFAULT_QUERY_PARAMETER" 1>/dev/null 2>&1
  else
    usage
  fi
}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || echo -ne "$@" | main
