#!/usr/bin/env bash

DEFAULT_WEB_BROWSER=brave-browser

DEFAULT_SEARCH_ENGINE_PAGE=https://gist.github.com/search

DEFAULT_QUERY_PARAMETER="q=@&ref=opensearch+l%3A%28OR+Text+OR+Markdown+OR+Shell%29&s=stars&o=desc"

usage(){
cat <<EOS
Usage:
   IN: echo systemd-nspawn | $0
  OUT: $DEFAULT_SEARCH_ENGINE_PAGE?q=systemd-nspawn&ref=opensearch+l%3A%28OR+Text+OR+Markdown+OR+Shell%29&s=stars&o=desc
EOS

exit 0

}

is_single_row(){
  #単一行チェック
  local CNT=0
  while read ln;do
    [ $(echo $ln | grep -c "0a") -eq 1 ] && CNT=$((CNT + 1))
  done < <(echo "$@" | xxd -ps -c1)
  [ $CNT -gt 1 ] || echo 0
  [ $CNT -gt 1 ] && echo 1
}

main(){
  n="$(cat -)";

  [ -z "$n" ] && usage

  if [[ $(is_single_row "$n") -eq 0 ]];then
    echo "$n" | xargs -I@ $DEFAULT_WEB_BROWSER "$DEFAULT_SEARCH_ENGINE_PAGE?$DEFAULT_QUERY_PARAMETER" 1>/dev/null 2>&1
  else
    usage
  fi
}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || echo -ne "$@" | main
