#!/usr/bin/env bash

DEFAULT_WEB_BROWSER=brave-browser

DEFAULT_SEARCH_ENGINE_PAGE="https://developer.android.com/s/results"

DEFAULT_QUERY_PARAMETER="q=@"

usage(){
cat <<EOS
Usage:
   IN: echo リストボックス | $0
  OUT: $DEFAULT_SEARCH_ENGINE_PAGE?q=%E3%83%AA%E3%82%B9%E3%83%88%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9
EOS

exit 0

}

is_single_row(){
  #単一行チェック
  local CNT=0
  while read ln;do
    [ $(echo $ln | grep -c "0a") -eq 1 ] && CNT=$((CNT + 1))
  done < <(echo "$@" | xxd -ps -c1)
  [ $CNT -gt 1 ] || echo 0
  [ $CNT -gt 1 ] && echo 1
}

main(){
  n="$(cat -)";

  [ -z "$n" ] && usage

  if [[ $(is_single_row "$n") -eq 0 ]];then
    echo "$n" | xargs -I@ $DEFAULT_WEB_BROWSER "$DEFAULT_SEARCH_ENGINE_PAGE?$DEFAULT_QUERY_PARAMETER" 1>/dev/null 2>&1
  else
    usage
  fi
}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || echo -ne "$@" | main
