#!/usr/bin/env bash

DEFAULT_WEB_BROWSER=brave-browser

DEFAULT_SEARCH_ENGINE_PAGE="https://ja.wikipedia.org/w/index.php"

DEFAULT_QUERY_PARAMETER="search=@&fulltext=1"

usage(){
cat <<EOS
Usage:
   IN: echo awk | $0
  OUT: $DEFAULT_SEARCH_ENGINE_PAGE?search=awk&fulltext=1&ns0=1
EOS

exit 0

}

is_single_row(){
  #単一行チェック
  local CNT=0
  while read ln;do
    [ $(echo $ln | grep -c "0a") -eq 1 ] && CNT=$((CNT + 1))
  done < <(echo "$@" | xxd -ps -c1)
  [ $CNT -gt 1 ] || echo 0
  [ $CNT -gt 1 ] && echo 1
}

main(){
  n="$(cat -)";

  [ -z "$n" ] && usage

  if [[ $(is_single_row "$n") -eq 0 ]];then
    echo "$n" | xargs -I@ $DEFAULT_WEB_BROWSER "$DEFAULT_SEARCH_ENGINE_PAGE?$DEFAULT_QUERY_PARAMETER" 1>/dev/null 2>&1
  else
    usage
  fi
}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || echo -ne "$@" | main
